name: "Clippy"

on:
  push:
    branches: ["main"]
    paths:
      - "**.rs"
      - ".github/workflows/clippy.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    paths:
      - "**.rs"
      - ".github/workflows/clippy.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  clippy:
    name: "Run scan"

    runs-on: "ubuntu-latest"

    permissions:
      security-events: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Install Rust"
        uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          components: "clippy"

      - name: "Install sarif tools"
        run: |
          cargo install clippy-sarif sarif-fmt

      - name: "Run clippy"
        run: |
          cargo clippy \
            --all-features \
            --all-targets \
            --tests \
            --message-format=json \
          | clippy-sarif | tee /tmp/clippy-result | sarif-fmt

      - name: "Upload results"
        uses: "github/codeql-action/upload-sarif@v3"
        with:
          sarif_file: "/tmp/clippy-result"
          wait-for-processing: true
